name: wakelock_plus_tizen
description: Tizen implementation of the wakelock plus plugin.
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: WakelockPlusTizenPlugin
        fileName: wakelock_plus_tizen_plugin.h
        dartPluginClass: WakelockPlusTizen

dependencies:
  flutter:
    sdk: flutter
  wakelock_platform_interface: ^0.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
