name: video_player_videohole
description: Flutter plugin for displaying inline video on Tizen TV devices.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole
version: 0.5.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VideoPlayerTizenPlugin
        fileName: video_player_tizen_plugin.h
        dartPluginClass: VideoPlayerTizen

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  video_player_platform_interface:
    hosted: https://pub.uscreen.cloud
    version: ">=6.2.2+3 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.0.0
